### ISSUE TITLE
Contract migrate \ update naming

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-contract#128]
All contracts besides NNS have `Migrate` method that call `Update` method of native management contract. NNS contract use `Update` method. `Migrate` name origins from [timer.go](https://github.com/nspcc-dev/neo-go/blob/master/examples/timer/timer.go) example. 

It will be a bit more convenient to have the same signature for contract update methods, I guess. Maybe it will be better to use `Update` in all contracts because it corresponds with management contract call. Thoughts?

/cc @fyrchik @roman-khimov @AnnaShaleva

**Comment by AnnaShaleva** [comment]
I don't see something that prevents us from renaming, and I also consider it's good to have unified methods naming that follows the Management's one. So I vote for `Update`.

**Comment by roman-khimov** [comment]
I think `Migrate` comes from Neo Legacy where it did have some meaning, data needed to be moved from one contract (with old hash) to another (with new hash). Now `Update` is more correct for N3 because contract's storage or hash doesn't change, it's just an update of code and/or manifest. @AnnaShaleva, we can do the same renaming in neo-go for consistency.
