### ISSUE TITLE
Merge some of the features in the mainline NNS contract

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-contract#260]
This is an issue for tracking differences between our NNS implementation and neo-go/C# one.
https://github.com/neo-project/non-native-contracts/tree/master/src/NameService

1. New record type: SOA (#125).
2. DNS RFC compliance #238, #183 and #139.
3. `getRecord`, `resolve` may return an array. The name for some functions is changed correspondingly.
4. Root domain no longer has a special interface (#139), but registration should be approved by a committee.
5. Arbitrary level domains #175 (each domain can have it's own admin, which approves subdomain registration). I think we stiil have some bugs regarding trasfer/adding records/expiration, need to discuss and write our spec here).

cc @roman-khimov

**Comment by roman-khimov** [comment]
> getRecord, resolve may return an array
> Root domain no longer has a special interface
> Arbitrary level domains

Wow. That's huge. Now I'm thinking if any NNS wrapper makes any sense at this stage, C# one is not used anywhere, NeoFS one differs enough that generic wrapper won't work for it.

**Comment by roman-khimov** [comment]
I think we've done everything we can here:
 * https://github.com/neo-project/non-native-contracts/pull/23
 * https://github.com/neo-project/non-native-contracts/pull/25
 * https://github.com/neo-project/non-native-contracts/pull/26
 * https://github.com/neo-project/non-native-contracts/pull/27
 * https://github.com/neo-project/non-native-contracts/pull/29

But we have diverged again since because of NeoFS requirements and likely that's to stay (C# contracts are not maintained at all). So, obsolete, wontfix.
