### ISSUE TITLE
Contract audit for inherent limitations and questionable practices

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-contract#304]
Review all contracts for how VM limits, types and storage schemas (!) affect them (like #297 or #263), questionable APIs (like netmap settings) and things we may not need or can improve (*X methods and notifications?, things like #290). My suspect list that needs to be checked:
 * audit List*
 * Balance TransferX
 * mint/burn
 * container delete/put/pueacl
 * container detached signatures
 * reputation get/list

It's not an extensive one and some of them might be OK, that's just what I have in my notes. Submit issues for problems detected.

**Comment by AnnaShaleva** [comment]
From the list mentioned above there're two items left unresolved, and here are my thoughts about it:
1. `mint/burn` methods of `Balance` contract. We can't replace them with more common `OnNEP17Payment` method (if that was the point), because these methods represent a reaction on transfer in mainchain (not in the sidechain where the `Balance` contract is deployed). @roman-khimov, what was your concern about these methods?
2. Container detached signatures. It's not the problem (from the `Container` contract's side) to pass and store signature along with the container as a single entity. But I suspect that the problem lays out of the contract scope and there's a meaningful reason for the signature to be detached from the container. @cthulhu-rider, is there any discussion about this design?

**Comment by roman-khimov** [comment]
1. I guess #318, it's about events.
2. My problem with it is that I see container as some kind of asset, almost NEP-11 kind of asset. You do not store signatures for them in some data fields, you sign transactions that do things with them. Current scheme detaches transaction signers from container owners (add some tokens into the mix and it'll be even more interesting), which is somewhat of a feature, but I'm not sure it's really needed.
