### ISSUE TITLE
Replace "Init" method with _deploy

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-contract#72]
This could be done after nspcc-dev/neo-go#1898 which will simplify things a bit (kinda RAII: if contract is deployed it's initialized).

**Comment by alexvanin** [comment]
> This could be done after nspcc-dev/neo-go#1898 which will simplify things a bit

Will there be a simple way to get smart contract script hash before deploy, so hashes can be passed as `_deploy` arguments? Otherwise deploy and initialization operations can't be merged.

There was a way to calculate script hash before deploy, but now it depends on wallet address and contract name in manifest and maybe some other things.

**Comment by roman-khimov** [comment]
```
$ ./bin/neo-go contract calc-hash -s NRBiGqBTmQyPY1RWM669Q9R8yssqS8YRyv --in examples/oracle/oracle.nef -m examples/oracle/oracle.json 
Contract hash: bca22434e0960b7ed9a066b124b00528b229dccc
```
Simple enough?

**Comment by alexvanin** [comment]
> Simple enough?

Missed that! It should work great then.
